<?php

return [
    'avatars_folder' => 'public/avatars',
    'image_folder' => 'public/images',
    'default_avatar' => 'public/avatars/default.jpg',
    'default_image' => 'public/images/default.jpg',
    'activated_user_status' => 1,
    'not_activated_user_status' => 0,
    'admin_permission' => 1,
    'user_permission' => 0,
    'pagination_limit' => 5,
    'admin' => 'admin',
    'female' => '0',
    'male' => '1',
    'other_gender' => '2',
    'rootcategory' => 0,
    'trending_product' => 1,
    'not_trending_product' => 0,
    'waiting_order' => 0,
    'done_order' => 1,
    'cancel_order' => 2,
    'currency_unit' => 1000,
    'currency' => 'VND',
];
