<?php

return [
    'avatars_folder' => 'public/avatars',
    'image_folder' => 'public/images',
    'suggest_image_folder' => 'public/suggets',
    'import_files_folder' => 'public/imports',
    'import_files_path' => 'storage/imports/',
    'default_avatar' => 'public/avatars/default.jpg',
    'default_image' => 'public/images/default.jpg',
    'default_suggest_image' => 'public/suggests/default.jpg',
    'activated_user_status' => 1,
    'not_activated_user_status' => 0,
    'admin_permission' => 1,
    'user_permission' => 0,
    'pagination_limit' => 5,
    'admin' => 'admin',
    'female' => '0',
    'male' => '1',
    'other_gender' => '2',
    'rootcategory' => 0,
    'trending_product' => 1,
    'not_trending_product' => 0,
    'waiting_order' => 0,
    'done_order' => 1,
    'cancel_order' => 2,
    'currency_unit' => 1000,
    'currency' => 'VND',
    'sugget_waiting' => 0,
    'sugget_accept' => 1,
    'sugget_reject' => 2,
    'facebook_app_id' => env('FACEBOOK_APP_ID', '654988298038475'),
    'front' => [
        'home-limit-take' => 3,
        'home-trending-limit' => 6,
        'product-page-limit' => 12,
        'limit' => 5,
    ],
];
